name: GitHub Actions CI/CD

on: 
  push:
    branches: '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: .NET Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"
      
      - name: Style Check
        run: if [[ $(dotnet format | wc -c) -gt 1 ]]; then exit 1; fi
        
      - name: Build and Static Code Analysis
        run: |
          dotnet build /p:RunCodeAnalysis=true --configuration Debug
          dotnet build /p:RunCodeAnalysis=true --configuration Release
      
      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --no-build

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Prepare Documentation
        run: |
          mkdir "./wiki"
          mv ./atm/obj/Debug/net6.0/*.md ./wiki

      - name: Publish Documentation
        uses: Andrew-Chen-Wang/github-wiki-action@v4
